services:
    draw.doctrine.repository.factory:
        class: "Doctrine\\ORM\\Repository\\DefaultRepositoryFactory"
        arguments:
            - []
            - '@service_container'
            - '@draw.doctrine.repository.factory.default'

    draw.doctrine.repository.factory.default:
        class: "Doctrine\\ORM\\Repository\\DefaultRepositoryFactory"
